### ISSUE TITLE
Option to use load over loadstring

### ISSUE THREAD

**Issue by ChildishGiant** [aryajur/many2one#1]
From 5.2 onwards loadstring is deprecated (https://www.lua.org/manual/5.2/manual.html#8.2) so this tool doesn't work

**Comment by aryajur** [comment]
Do you still have this issue? loadstring is only used when it is available in the code otherwise it uses load.

**Comment by ChildishGiant** [comment]
Ah, I'm exporting a library to then drop into another runtime. The system I'm running many2one on may still support loadstring but where I was running it didn't.

**Comment by aryajur** [comment]
Ok, that was the assumption that the lua interpreter you use to run many2one should be the same that is used to run your actual Lua code so all the dependency  extraction also works as it would for the actual Lua code.
         So do you have any suggestion for improvement of the methodology?  Otherwise we can probably close this issue.

**Comment by aryajur** [comment]
I am going to close the issue.

**Comment by ChildishGiant** [comment]
Maybe a flag to force the usage of load instead of loadstring?

**Comment by aryajur** [comment]
How about if I check the Lua Version and do loadstring on Lua 5.1. I want to explore ways to make it automatic.

**Comment by aryajur** [comment]
Ok I think I will add a switch to control this functionality. If that flag is there it will be used to force Lua 5.2+ semantics or Lua 5.1 semantics otherwise if not present it will behave as it does today.

**Comment by aryajur** [comment]
Added the flags lua51 and lua52p. Is specified in the command line will force the semantics of the lua version. Commit: [https://github.com/aryajur/many2one/commit/f02f9ebb2bedd98ed889c79569ff72c83f1fa756](url)
